package Error

const (
	NULL        = 0
	SYSTEM      = 1
	SYSTEM_TEST = 2

	CLIENT_INVALID_REQUEST = 6

	REGISTER_USERNAME_EXISTED      = 11
	REGISTER_EMAIL_EXISTED         = 12
	REGISTER_VERIFY_USER_NOT_EXIST = 13
	REGISTER_INVALID_USERNAME      = 14
	REGISTER_USERNAME_TOO_SHORT    = 15
	REGISTER_USERNAME_TOO_LENGTH   = 16
	REGISTER_INVALID_EMAIL         = 17
	REGISTER_INVALID_PASSWORD      = 18
	REGISTER_PASSWORD_TOO_SHORT    = 19

	LOGIN_USER_NOT_EXIST     = 21
	LOGIN_PASSWORD_NOT_MATCH = 22

	USERNAME_IS_EMPTY = 31
	EMAIL_IS_EMPTY    = 32
	PASSWORD_IS_EMPTY = 33

	AUTHORIZATION_INVALID = 41
	AUTHORIZATION_EXPIRED = 42
	NOT_LOGGED_IN         = 43
)
