package Error

const (
	NULL        = 0
	SYSTEM      = 1
	SYSTEM_TEST = 2

	CLIENT_INVALID_REQUEST = 6

	USERNAME_EXISTED               = 11
	EMAIL_EXISTED                  = 12
	REGISTER_VERIFY_USER_NOT_EXIST = 13
	INVALID_USERNAME               = 14
	USERNAME_TOO_SHORT             = 15
	USERNAME_TOO_LONG              = 16
	INVALID_EMAIL_FORMAT           = 17
	INVALID_PASSWORD               = 18
	PASSWORD_TOO_SHORT             = 19

	USER_NOT_EXIST     = 21
	PASSWORD_NOT_MATCH = 22

	USERNAME_IS_EMPTY     = 31
	EMAIL_IS_EMPTY        = 32
	PASSWORD_IS_EMPTY     = 33
	NEW_PASSWORD_IS_EMPTY = 34

	AUTHORIZATION_INVALID = 41
	AUTHORIZATION_EXPIRED = 42
	NOT_LOGGED_IN         = 43
	USER_NOT_MATCH        = 44

	EMAIL_VERIFY_NOT_EXIST           = 51
	EMAIL_VERIFICATION_CODE_IS_EMPTY = 52
	INVALID_EMAIL_VERIFICATION_KEY   = 53
)
